name: PlantUML Diagrams

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  generate-diagrams:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: adopt # Required parameter for v2

      - name: Install PlantUML
        run: |
          # Download and install PlantUML JAR (more reliable than apt)
          curl -O https://plantuml.com/download/plantuml-1.2022.0.jar
          java -jar plantuml-1.2022.0.jar

      - name: Create output directory
        run: mkdir -p img

      - name: Generate Diagrams
        run: |
          java -jar plantuml-1.2022.0.jar diagrams/*.puml -o img/

      - name: Commit Diagrams
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add diagrams/**/*.png
          git commit -m "Automated diagram generation" || echo "No changes to commit"
          git push origin main
        if: success()
