name: PlantUML Diagrams
on:
  push:
    branches:
      - master
    paths:
      - "diagrams/**"
  pull_request:
    branches:
      - master
    paths:
      - "diagrams/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-diagrams:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          submodules: recursive

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Install PlantUML
        run: |
          sudo apt-get update
          sudo apt-get install -y plantuml

      - name: Debug files structure
        run: |
          echo "=== Current directory ==="
          pwd
          echo "=== Files in diagrams ==="
          ls -la diagrams/
          echo "=== Files in c4-plantuml ==="
          ls -la c4-plantuml/ || echo "c4-plantuml not found"
          echo "=== First 10 lines of diagram ==="
          head -10 diagrams/agrotech.puml

      - name: Generate Diagrams
        run: |
          mkdir -p img
          plantuml -verbose diagrams/*.puml -o ../img/

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push diagrams
        if: steps.verify-changed-files.outputs.changed == 'true' && github.event_name == 'push'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add img/**/*.png img/**/*.svg
          git commit -m "🤖 Auto-generate PlantUML diagrams [skip ci]"
          git push
